"""create_content_management_tables

Revision ID: a9d8d7a3296c
Revises: 0001_create_categories
Create Date: 2026-07-14 17:41:38.285296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d8d7a3296c'
down_revision: Union[str, Sequence[str], None] = '0001_create_categories'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_calls',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('modality', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'year', 'modality', name='uq_call_number_year_modality')
    )
    op.create_index(op.f('ix_tbl_calls_id'), 'tbl_calls', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_calls_modality'), 'tbl_calls', ['modality'], unique=False)
    op.create_index(op.f('ix_tbl_calls_number'), 'tbl_calls', ['number'], unique=False)
    op.create_index(op.f('ix_tbl_calls_status'), 'tbl_calls', ['status'], unique=False)
    op.create_index(op.f('ix_tbl_calls_title'), 'tbl_calls', ['title'], unique=False)
    op.create_index(op.f('ix_tbl_calls_year'), 'tbl_calls', ['year'], unique=False)
    op.create_table('tbl_contact_messages',
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_contact_messages_email'), 'tbl_contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_tbl_contact_messages_full_name'), 'tbl_contact_messages', ['full_name'], unique=False)
    op.create_index(op.f('ix_tbl_contact_messages_id'), 'tbl_contact_messages', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_contact_messages_status'), 'tbl_contact_messages', ['status'], unique=False)
    op.create_index(op.f('ix_tbl_contact_messages_subject'), 'tbl_contact_messages', ['subject'], unique=False)
    op.create_table('tbl_news',
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_news_id'), 'tbl_news', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_news_published_date'), 'tbl_news', ['published_date'], unique=False)
    op.create_index(op.f('ix_tbl_news_status'), 'tbl_news', ['status'], unique=False)
    op.create_index(op.f('ix_tbl_news_title'), 'tbl_news', ['title'], unique=False)
    op.create_table('tbl_resolutions',
    sa.Column('number', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('resolution_type', sa.String(length=120), nullable=False),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', 'year', 'resolution_type', name='uq_resolution_number_year_type')
    )
    op.create_index(op.f('ix_tbl_resolutions_id'), 'tbl_resolutions', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_resolutions_number'), 'tbl_resolutions', ['number'], unique=False)
    op.create_index(op.f('ix_tbl_resolutions_resolution_date'), 'tbl_resolutions', ['resolution_date'], unique=False)
    op.create_index(op.f('ix_tbl_resolutions_resolution_type'), 'tbl_resolutions', ['resolution_type'], unique=False)
    op.create_index(op.f('ix_tbl_resolutions_status'), 'tbl_resolutions', ['status'], unique=False)
    op.create_index(op.f('ix_tbl_resolutions_year'), 'tbl_resolutions', ['year'], unique=False)
    op.create_table('tbl_call_stages',
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('stage_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['tbl_calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('call_id', 'display_order', name='uq_call_stage_order')
    )
    op.create_index(op.f('ix_tbl_call_stages_call_id'), 'tbl_call_stages', ['call_id'], unique=False)
    op.create_index(op.f('ix_tbl_call_stages_id'), 'tbl_call_stages', ['id'], unique=False)
    op.create_table('tbl_documents',
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('file_type', sa.String(length=30), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('group_name', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('call_stage_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['call_stage_id'], ['tbl_call_stages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['tbl_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_documents_call_stage_id'), 'tbl_documents', ['call_stage_id'], unique=False)
    op.create_index(op.f('ix_tbl_documents_category_id'), 'tbl_documents', ['category_id'], unique=False)
    op.create_index(op.f('ix_tbl_documents_group_name'), 'tbl_documents', ['group_name'], unique=False)
    op.create_index(op.f('ix_tbl_documents_id'), 'tbl_documents', ['id'], unique=False)
    op.create_index(op.f('ix_tbl_documents_publication_date'), 'tbl_documents', ['publication_date'], unique=False)
    op.create_index(op.f('ix_tbl_documents_status'), 'tbl_documents', ['status'], unique=False)
    op.create_index(op.f('ix_tbl_documents_title'), 'tbl_documents', ['title'], unique=False)
    op.create_index(op.f('ix_tbl_documents_year'), 'tbl_documents', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_documents_year'), table_name='tbl_documents')
    op.drop_index(op.f('ix_tbl_documents_title'), table_name='tbl_documents')
    op.drop_index(op.f('ix_tbl_documents_status'), table_name='tbl_documents')
    op.drop_index(op.f('ix_tbl_documents_publication_date'), table_name='tbl_documents')
    op.drop_index(op.f('ix_tbl_documents_id'), table_name='tbl_documents')
    op.drop_index(op.f('ix_tbl_documents_group_name'), table_name='tbl_documents')
    op.drop_index(op.f('ix_tbl_documents_category_id'), table_name='tbl_documents')
    op.drop_index(op.f('ix_tbl_documents_call_stage_id'), table_name='tbl_documents')
    op.drop_table('tbl_documents')
    op.drop_index(op.f('ix_tbl_call_stages_id'), table_name='tbl_call_stages')
    op.drop_index(op.f('ix_tbl_call_stages_call_id'), table_name='tbl_call_stages')
    op.drop_table('tbl_call_stages')
    op.drop_index(op.f('ix_tbl_resolutions_year'), table_name='tbl_resolutions')
    op.drop_index(op.f('ix_tbl_resolutions_status'), table_name='tbl_resolutions')
    op.drop_index(op.f('ix_tbl_resolutions_resolution_type'), table_name='tbl_resolutions')
    op.drop_index(op.f('ix_tbl_resolutions_resolution_date'), table_name='tbl_resolutions')
    op.drop_index(op.f('ix_tbl_resolutions_number'), table_name='tbl_resolutions')
    op.drop_index(op.f('ix_tbl_resolutions_id'), table_name='tbl_resolutions')
    op.drop_table('tbl_resolutions')
    op.drop_index(op.f('ix_tbl_news_title'), table_name='tbl_news')
    op.drop_index(op.f('ix_tbl_news_status'), table_name='tbl_news')
    op.drop_index(op.f('ix_tbl_news_published_date'), table_name='tbl_news')
    op.drop_index(op.f('ix_tbl_news_id'), table_name='tbl_news')
    op.drop_table('tbl_news')
    op.drop_index(op.f('ix_tbl_contact_messages_subject'), table_name='tbl_contact_messages')
    op.drop_index(op.f('ix_tbl_contact_messages_status'), table_name='tbl_contact_messages')
    op.drop_index(op.f('ix_tbl_contact_messages_id'), table_name='tbl_contact_messages')
    op.drop_index(op.f('ix_tbl_contact_messages_full_name'), table_name='tbl_contact_messages')
    op.drop_index(op.f('ix_tbl_contact_messages_email'), table_name='tbl_contact_messages')
    op.drop_table('tbl_contact_messages')
    op.drop_index(op.f('ix_tbl_calls_year'), table_name='tbl_calls')
    op.drop_index(op.f('ix_tbl_calls_title'), table_name='tbl_calls')
    op.drop_index(op.f('ix_tbl_calls_status'), table_name='tbl_calls')
    op.drop_index(op.f('ix_tbl_calls_number'), table_name='tbl_calls')
    op.drop_index(op.f('ix_tbl_calls_modality'), table_name='tbl_calls')
    op.drop_index(op.f('ix_tbl_calls_id'), table_name='tbl_calls')
    op.drop_table('tbl_calls')
    # ### end Alembic commands ###
